name: Deploy to S3 (Root User)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AKIA4N7K }}
          aws-secret-access-key: ${{ secrets.nyffUM/vo7Ksn87+zURMBYQv1aCOQWYGZ5OKSsiE }}
          aws-region: ${{ secrets.US East (N. Virginia) us-east-1 }}

      - name: Deploy to S3
        run: aws s3 sync . s3://${{ secrets.S3_BUCKET }} --delete
